---
abstract: 'OAuth version 2 client'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OAuth2
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request: 0
  HTTP::Status: 0
  JSON: 0
  LWP::UserAgent: 0
  Scalar::Util: 0
  Test::More: 0
  URI: 0
  YAML: 0
version: 0.57
